In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [3]:
list1=[45,25,36,5]
arr1 = np.array(list1)
arr1

array([45, 25, 36,  5])

In [4]:
arr1.ndim

1

In [5]:
arr1.shape

(4,)

In [11]:
arr2 = np.array([[45,25,32], [42,35,100],[80,72,56],[45,20,21]])
arr2


array([[ 45,  25,  32],
       [ 42,  35, 100],
       [ 80,  72,  56],
       [ 45,  20,  21]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(4, 3)

In [14]:
np.linspace(10,30)

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [15]:
np.linspace(10,30,15)

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        , 21.42857143, 22.85714286,
       24.28571429, 25.71428571, 27.14285714, 28.57142857, 30.        ])

In [29]:
np.ones(10,dtype = 'int64')*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5], dtype=int64)

In [31]:
np.ones((10),dtype = 'int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.eye(16)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [43]:
arr4 = np.arange(1,101,3)
arr4

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [53]:
np.random.seed(1)
arr5 = np.random.randint(15,45,70)
arr5

array([20, 26, 27, 23, 24, 26, 20, 30, 15, 31, 16, 27, 22, 28, 43, 21, 40,
       33, 35, 20, 33, 35, 26, 43, 25, 43, 44, 29, 33, 19, 38, 38, 24, 32,
       38, 15, 37, 28, 24, 24, 22, 44, 37, 40, 16, 15, 43, 32, 23, 39, 28,
       34, 30, 25, 40, 23, 22, 18, 21, 36, 32, 40, 18, 19, 39, 32, 26, 27,
       41, 35])

In [54]:
len(arr5)

70

In [56]:
arr5 = arr5.reshape(7,10)
arr5
# to return two dimensional back to one dimension arr5 = arr5.flatten


array([[20, 26, 27, 23, 24, 26, 20, 30, 15, 31],
       [16, 27, 22, 28, 43, 21, 40, 33, 35, 20],
       [33, 35, 26, 43, 25, 43, 44, 29, 33, 19],
       [38, 38, 24, 32, 38, 15, 37, 28, 24, 24],
       [22, 44, 37, 40, 16, 15, 43, 32, 23, 39],
       [28, 34, 30, 25, 40, 23, 22, 18, 21, 36],
       [32, 40, 18, 19, 39, 32, 26, 27, 41, 35]])

In [57]:
arr5[2,4]

25

In [58]:
arr5[2:6,3:6]

array([[43, 25, 43],
       [32, 38, 15],
       [40, 16, 15],
       [25, 40, 23]])

In [61]:
arr5[2:6,3:6] = 15
arr5

array([[20, 26, 27, 23, 24, 26, 20, 30, 15, 31],
       [16, 27, 22, 28, 43, 21, 40, 33, 35, 20],
       [33, 35, 26, 15, 15, 15, 44, 29, 33, 19],
       [38, 38, 24, 15, 15, 15, 37, 28, 24, 24],
       [22, 44, 37, 15, 15, 15, 43, 32, 23, 39],
       [28, 34, 30, 15, 15, 15, 22, 18, 21, 36],
       [32, 40, 18, 19, 39, 32, 26, 27, 41, 35]])

In [66]:
arr5[arr5 >= 25]

array([26, 27, 26, 30, 31, 27, 28, 43, 40, 33, 35, 33, 35, 26, 44, 29, 33,
       38, 38, 37, 28, 44, 37, 43, 32, 39, 28, 34, 30, 36, 32, 40, 39, 32,
       26, 27, 41, 35])

In [67]:
arr5[arr5 <= 25]

array([20, 23, 24, 20, 15, 16, 22, 21, 20, 15, 15, 15, 19, 24, 15, 15, 15,
       24, 24, 22, 15, 15, 15, 23, 15, 15, 15, 22, 18, 21, 18, 19])

In [69]:
np.sum(arr5)

1877

In [72]:
round(np.mean(arr5),2)

26.81

In [73]:
np.median(arr5)

26.0

In [74]:
np.log10(arr5)

array([[1.30103   , 1.41497335, 1.43136376, 1.36172784, 1.38021124,
        1.41497335, 1.30103   , 1.47712125, 1.17609126, 1.49136169],
       [1.20411998, 1.43136376, 1.34242268, 1.44715803, 1.63346846,
        1.32221929, 1.60205999, 1.51851394, 1.54406804, 1.30103   ],
       [1.51851394, 1.54406804, 1.41497335, 1.17609126, 1.17609126,
        1.17609126, 1.64345268, 1.462398  , 1.51851394, 1.2787536 ],
       [1.5797836 , 1.5797836 , 1.38021124, 1.17609126, 1.17609126,
        1.17609126, 1.56820172, 1.44715803, 1.38021124, 1.38021124],
       [1.34242268, 1.64345268, 1.56820172, 1.17609126, 1.17609126,
        1.17609126, 1.63346846, 1.50514998, 1.36172784, 1.59106461],
       [1.44715803, 1.53147892, 1.47712125, 1.17609126, 1.17609126,
        1.17609126, 1.34242268, 1.25527251, 1.32221929, 1.5563025 ],
       [1.50514998, 1.60205999, 1.25527251, 1.2787536 , 1.59106461,
        1.50514998, 1.41497335, 1.43136376, 1.61278386, 1.54406804]])

In [75]:
np.sqrt(arr5)

array([[4.47213595, 5.09901951, 5.19615242, 4.79583152, 4.89897949,
        5.09901951, 4.47213595, 5.47722558, 3.87298335, 5.56776436],
       [4.        , 5.19615242, 4.69041576, 5.29150262, 6.55743852,
        4.58257569, 6.32455532, 5.74456265, 5.91607978, 4.47213595],
       [5.74456265, 5.91607978, 5.09901951, 3.87298335, 3.87298335,
        3.87298335, 6.63324958, 5.38516481, 5.74456265, 4.35889894],
       [6.164414  , 6.164414  , 4.89897949, 3.87298335, 3.87298335,
        3.87298335, 6.08276253, 5.29150262, 4.89897949, 4.89897949],
       [4.69041576, 6.63324958, 6.08276253, 3.87298335, 3.87298335,
        3.87298335, 6.55743852, 5.65685425, 4.79583152, 6.244998  ],
       [5.29150262, 5.83095189, 5.47722558, 3.87298335, 3.87298335,
        3.87298335, 4.69041576, 4.24264069, 4.58257569, 6.        ],
       [5.65685425, 6.32455532, 4.24264069, 4.35889894, 6.244998  ,
        5.65685425, 5.09901951, 5.19615242, 6.40312424, 5.91607978]])

In [77]:
np.sqrt(np.median(arr5))

5.0990195135927845

In [78]:
np.percentile(arr5,50)

26.0

In [79]:
np.max(arr5)

44

In [80]:
np.argmax(arr5)

26

In [81]:
np.min(arr5)

15

In [82]:
np.argmin(arr5)

8

In [83]:
 # panda is a cleaning or manipulation of data its is divided into two parts(series or data frame)
    # series : is one label directional  array
    # Dataframe : is two label directional array
    
    
    
import pandas as pd

In [86]:
fruits = ['orange', 'pawpaw', 'coconut', 'strawberry']
values = [450,400,250,600]
s1 = pd.Series(data = values, index = fruits)
s1

orange        450
pawpaw        400
coconut       250
strawberry    600
dtype: int64

In [87]:
s1['pawpaw']

400

In [88]:
s2 = pd.Series(data = values)
s2

0    450
1    400
2    250
3    600
dtype: int64

In [89]:
s2[1]

400